import coreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

// Named rather than exported anonymously, which eslint's own
// import/no-anonymous-default-export asks for and `next lint` never checked because it
// does not lint its own config (#139).
const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "data/**",
      "worker/**",
      "deploy/**",
      // GENERATED by Next, regenerated on every build, and it carries a triple-slash
      // reference that our own rules reject. `next lint` excluded it implicitly; once
      // the script calls eslint directly, the exclusion has to be written down.
      "next-env.d.ts",
    ],
  },
  ...coreWebVitals,
  ...nextTypescript,
  {
    rules: {
      // The transparent senders load lazily through createRequire because they
      // drag in utxo-lib and the t2z prover. See src/lib/zcash/send.ts.
      "@typescript-eslint/no-require-imports": "off",

      // AN UNUSED IMPORT IS DEAD CODE AND THIS RULE ALREADY FOUND THEM - as WARNINGS, and
      // eslint exits 0 on warnings, so `npm run lint` passed and CI went green over seven of
      // them. Six had accumulated in page.tsx alone as logic moved out to faucetPhase.ts and
      // the imports stayed. A rule nothing fails on is a rule nobody reads.
      // Scoped to this rule: the react-hooks/exhaustive-deps warnings in page.tsx are a
      // separate question and turning them into errors is not this change.
      "@typescript-eslint/no-unused-vars": "error",

      // eslint-config-next 16 turns on the React Compiler rules. We have NOT adopted
      // the compiler, so two of them are switched off deliberately and by name rather
      // than by disabling the set (#139).
      //
      // KEPT ON, because they each caught a real bug in #263:
      //   react-hooks/purity  Date.now() in a useState initialiser ran during render,
      //                       giving the server's clock on SSR and the client's on
      //                       hydration.
      //   react-hooks/refs    the progress bar read a ref that is cleared
      //                       synchronously in a finally, so a render could show a
      //                       finished bar under a UI still saying submitting.
      //
      // OFF, because they are the compiler's stance on patterns that are correct
      // without it, and satisfying them means restructuring a 700-line component whose
      // only gate is the browser smoke. Adopting the compiler is its own project with
      // its own testing, not a drive-by on a config bump.
      "react-hooks/set-state-in-effect": "off", // reading storage on mount and setting state
      "react-hooks/immutability": "off", // an effect referring to a const declared below it
    },
  },
  {
    // Test files spawn helpers and poke at internals; the app rules do not fit.
    files: ["**/*.test.ts", "scripts/**"],
    rules: { "@typescript-eslint/no-explicit-any": "off" },
  },
];

export default config;
