import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

// Named rather than exported anonymously, which eslint's own
// import/no-anonymous-default-export asks for and `next lint` never checked because it
// does not lint its own config (#139).
const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "data/**",
      "worker/**",
      "deploy/**",
      // GENERATED by Next, regenerated on every build, and it carries a triple-slash
      // reference that our own rules reject. `next lint` excluded it implicitly; once
      // the script calls eslint directly, the exclusion has to be written down.
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // The transparent senders load lazily through createRequire because they
      // drag in utxo-lib and the t2z prover. See src/lib/zcash/send.ts.
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  {
    // Test files spawn helpers and poke at internals; the app rules do not fit.
    files: ["**/*.test.ts", "scripts/**"],
    rules: { "@typescript-eslint/no-explicit-any": "off" },
  },
];

export default config;
