import { test } from "node:test";
import assert from "node:assert/strict";
import { base58check as base58checkFactory, bech32, bech32m } from "@scure/base";
import { sha256 } from "@noble/hashes/sha2.js";
import { validateTestnetAddress } from "./address.ts";
import { generateTransparentAccount } from "./keys.ts";

// Vectors built with the same coders the validator decodes with, so their
// checksums are genuinely valid. Payload bytes are arbitrary but correctly
// sized: the validator's contract is checksum + version/size, not receiver
// semantics.
const b58c = base58checkFactory(sha256);
const seq = (n: number, fill: number) => Uint8Array.from({ length: n }, (_, i) => (i * 7 + fill) & 0xff);

const UNIFIED = bech32m.encode("utest", bech32m.toWords(seq(96, 3)), 1023);
const UNIFIED_REGTEST = bech32m.encode("uregtest", bech32m.toWords(seq(96, 5)), 1023);
const SAPLING = bech32.encode("ztestsapling", bech32.toWords(seq(43, 9)), 1023);
const SAPLING_REGTEST = bech32.encode("zregtestsapling", bech32.toWords(seq(43, 11)), 1023);
const P2PKH = b58c.encode(Uint8Array.from([0x1d, 0x25, ...seq(20, 1)]));
const P2SH = b58c.encode(Uint8Array.from([0x1c, 0xba, ...seq(20, 2)]));

/** Corrupt one character of the data part, which must break the checksum. */
function flip(addr: string): string {
  const i = addr.length - 3;
  const alt = addr[i] === "q" ? "p" : "q";
  return addr.slice(0, i) + alt + addr.slice(i + 1);
}

test("accepts checksum-valid unified, sapling, and transparent addresses", () => {
  assert.deepEqual(validateTestnetAddress(UNIFIED), { valid: true, kind: "unified", shielded: true });
  assert.deepEqual(validateTestnetAddress(SAPLING), { valid: true, kind: "sapling", shielded: true });
  assert.deepEqual(validateTestnetAddress(P2PKH), { valid: true, kind: "transparent", shielded: false });
  assert.deepEqual(validateTestnetAddress(P2SH), { valid: true, kind: "transparent", shielded: false });
});

test("accepts the regtest unified and sapling prefixes", () => {
  assert.equal(validateTestnetAddress(UNIFIED_REGTEST).valid, true);
  assert.equal(validateTestnetAddress(SAPLING_REGTEST).valid, true);
});

test("accepts a tm address freshly generated by our own key code", () => {
  const { address } = generateTransparentAccount();
  assert.deepEqual(validateTestnetAddress(address), { valid: true, kind: "transparent", shielded: false });
});

test("trims surrounding whitespace before validating", () => {
  assert.equal(validateTestnetAddress("  " + P2PKH + "\n").valid, true);
});

test("one flipped character fails the checksum, coins cannot go to a typo", () => {
  for (const [addr, what] of [
    [flip(UNIFIED), "unified"],
    [flip(SAPLING), "sapling"],
    [flip(P2PKH), "transparent"],
    [flip(P2SH), "transparent"],
  ] as const) {
    const v = validateTestnetAddress(addr);
    assert.equal(v.valid, false, `${what}: ${addr}`);
    assert.match(v.reason ?? "", /checksum/i, what);
  }
});

test("rejects a sapling payload of the wrong size even with a good checksum", () => {
  const wrongSize = bech32.encode("ztestsapling", bech32.toWords(seq(32, 4)), 1023);
  const v = validateTestnetAddress(wrongSize);
  assert.equal(v.valid, false);
  assert.match(v.reason ?? "", /payload size/i);
});

test("rejects a unified payload far too short to hold a receiver", () => {
  const tiny = bech32m.encode("utest", bech32m.toWords(seq(16, 4)), 1023);
  const v = validateTestnetAddress(tiny);
  assert.equal(v.valid, false);
  assert.match(v.reason ?? "", /too short/i);
});

test("rejects every mainnet prefix with the mainnet reason", () => {
  const mainnet = [
    bech32m.encode("u", bech32m.toWords(seq(96, 3)), 1023), // u1...
    bech32.encode("zs", bech32.toWords(seq(43, 9)), 1023), // zs1...
    b58c.encode(Uint8Array.from([0x1c, 0xb8, ...seq(20, 1)])), // t1...
    b58c.encode(Uint8Array.from([0x1c, 0xbd, ...seq(20, 2)])), // t3...
  ];
  for (const addr of mainnet) {
    const v = validateTestnetAddress(addr);
    assert.equal(v.valid, false, addr);
    assert.match(v.reason ?? "", /mainnet/i, addr);
  }
});

test("rejects empty and whitespace-only input", () => {
  for (const addr of ["", "   ", "\t\n"]) {
    const v = validateTestnetAddress(addr);
    assert.equal(v.valid, false);
    assert.match(v.reason ?? "", /empty/i);
  }
});

test("rejects an address over 512 chars as too long", () => {
  const v = validateTestnetAddress("utest1" + "q".repeat(600));
  assert.equal(v.valid, false);
  assert.match(v.reason ?? "", /too long/i);
});

test("rejects mixed-case bech32, per spec it is all-lower or all-upper", () => {
  const mixed = UNIFIED.slice(0, -10) + UNIFIED.slice(-10).toUpperCase();
  const v = validateTestnetAddress(mixed);
  assert.equal(v.valid, false);
  assert.match(v.reason ?? "", /checksum/i);
});

test("rejects garbage with the unrecognized reason", () => {
  for (const addr of ["hello", "bc1qxyz", "0x52908400098527886E0F7030069857D2E4169EE7", "ztest1qqqqqqqq"]) {
    const v = validateTestnetAddress(addr);
    assert.equal(v.valid, false, addr);
    assert.match(v.reason ?? "", /unrecognized/i, addr);
  }
});
