import { test } from "node:test";
import assert from "node:assert/strict";
import { base58check as base58checkFactory, bech32, bech32m } from "@scure/base";
import { sha256 } from "@noble/hashes/sha2.js";
import { validateTestnetAddress } from "./address.ts";
import { generateTransparentAccount } from "./keys.ts";

// Vectors built with the same coders the validator decodes with, so their
// checksums are genuinely valid. Payload bytes are arbitrary but correctly
// sized: the validator's contract is checksum + version/size, not receiver
// semantics.
const b58c = base58checkFactory(sha256);
const seq = (n: number, fill: number) => Uint8Array.from({ length: n }, (_, i) => (i * 7 + fill) & 0xff);

const UNIFIED = bech32m.encode("utest", bech32m.toWords(seq(96, 3)), 1023);
const UNIFIED_REGTEST = bech32m.encode("uregtest", bech32m.toWords(seq(96, 5)), 1023);
const SAPLING = bech32.encode("ztestsapling", bech32.toWords(seq(43, 9)), 1023);
const SAPLING_REGTEST = bech32.encode("zregtestsapling", bech32.toWords(seq(43, 11)), 1023);
const P2PKH = b58c.encode(Uint8Array.from([0x1d, 0x25, ...seq(20, 1)]));
const P2SH = b58c.encode(Uint8Array.from([0x1c, 0xba, ...seq(20, 2)]));

/** Corrupt one character of the data part, which must break the checksum. */
function flip(addr: string): string {
  const i = addr.length - 3;
  const alt = addr[i] === "q" ? "p" : "q";
  return addr.slice(0, i) + alt + addr.slice(i + 1);
}

test("accepts checksum-valid unified and transparent addresses", () => {
  assert.deepEqual(validateTestnetAddress(UNIFIED), { valid: true, kind: "unified", shielded: true });
  assert.deepEqual(validateTestnetAddress(P2PKH), { valid: true, kind: "transparent", shielded: false });
  assert.deepEqual(validateTestnetAddress(P2SH), { valid: true, kind: "transparent", shielded: false });
});

test("a WELL-FORMED sapling address is refused here, not eight steps later with a 502", () => {
  // The wallet's notes are Ironwood. Paying Sapling crosses pools, reveals the amount,
  // and the send goes out under FullPrivacy, so zallet declines to build it. That reached
  // two users on 2026-09-10 as a bare 502 AFTER they had solved the proof-of-work, and
  // neither reported it - they were found in the logs while chasing something else.
  // Address validation is step 1 and the gate is step 2, so refusing here costs them
  // nothing.
  const r = validateTestnetAddress(SAPLING);
  assert.equal(r.valid, false, "a sapling address must not be accepted while it cannot be paid");
  if (r.valid) return;
  assert.match(r.reason, /Sapling addresses cannot be paid/);
  // And it must say what to use instead. A refusal with no way forward is the same dead
  // end as the 502, politely worded.
  assert.match(r.reason, /utest1/, "the refusal must name the address type that does work");
});

test("a MALFORMED sapling address still reads as malformed, not as unsupported", () => {
  // The order matters and is easy to lose: refuse-because-unsupported placed before the
  // checksum and payload checks would tell someone with a typo that Sapling is the
  // problem, and they would go and find a second broken address.
  assert.match(
    (validateTestnetAddress(flip(SAPLING)) as { valid: false; reason: string }).reason,
    /Malformed Sapling address/,
  );
});

test("accepts the regtest unified prefix, and refuses regtest sapling for the same reason", () => {
  assert.equal(validateTestnetAddress(UNIFIED_REGTEST).valid, true);
  // The pool problem is a property of the wallet's notes, not of which net it is on.
  assert.equal(validateTestnetAddress(SAPLING_REGTEST).valid, false);
});

test("accepts a tm address freshly generated by our own key code", () => {
  const { address } = generateTransparentAccount();
  assert.deepEqual(validateTestnetAddress(address), { valid: true, kind: "transparent", shielded: false });
});

test("trims surrounding whitespace before validating", () => {
  assert.equal(validateTestnetAddress("  " + P2PKH + "\n").valid, true);
});

test("one flipped character fails the checksum, coins cannot go to a typo", () => {
  for (const [addr, what] of [
    [flip(UNIFIED), "unified"],
    [flip(SAPLING), "sapling"],
    [flip(P2PKH), "transparent"],
    [flip(P2SH), "transparent"],
  ] as const) {
    const v = validateTestnetAddress(addr);
    assert.equal(v.valid, false, `${what}: ${addr}`);
    assert.match(v.reason ?? "", /checksum/i, what);
  }
});

test("rejects a sapling payload of the wrong size even with a good checksum", () => {
  const wrongSize = bech32.encode("ztestsapling", bech32.toWords(seq(32, 4)), 1023);
  const v = validateTestnetAddress(wrongSize);
  assert.equal(v.valid, false);
  assert.match(v.reason ?? "", /payload size/i);
});

test("rejects a unified payload far too short to hold a receiver", () => {
  const tiny = bech32m.encode("utest", bech32m.toWords(seq(16, 4)), 1023);
  const v = validateTestnetAddress(tiny);
  assert.equal(v.valid, false);
  assert.match(v.reason ?? "", /too short/i);
});

test("rejects every mainnet prefix with the mainnet reason", () => {
  const mainnet = [
    bech32m.encode("u", bech32m.toWords(seq(96, 3)), 1023), // u1...
    bech32.encode("zs", bech32.toWords(seq(43, 9)), 1023), // zs1...
    b58c.encode(Uint8Array.from([0x1c, 0xb8, ...seq(20, 1)])), // t1...
    b58c.encode(Uint8Array.from([0x1c, 0xbd, ...seq(20, 2)])), // t3...
  ];
  for (const addr of mainnet) {
    const v = validateTestnetAddress(addr);
    assert.equal(v.valid, false, addr);
    assert.match(v.reason ?? "", /mainnet/i, addr);
  }
});

test("rejects empty and whitespace-only input", () => {
  for (const addr of ["", "   ", "\t\n"]) {
    const v = validateTestnetAddress(addr);
    assert.equal(v.valid, false);
    assert.match(v.reason ?? "", /empty/i);
  }
});

test("rejects an address over 512 chars as too long", () => {
  const v = validateTestnetAddress("utest1" + "q".repeat(600));
  assert.equal(v.valid, false);
  assert.match(v.reason ?? "", /too long/i);
});

test("rejects mixed-case bech32, per spec it is all-lower or all-upper", () => {
  const mixed = UNIFIED.slice(0, -10) + UNIFIED.slice(-10).toUpperCase();
  const v = validateTestnetAddress(mixed);
  assert.equal(v.valid, false);
  assert.match(v.reason ?? "", /checksum/i);
});

test("rejects garbage with the unrecognized reason", () => {
  for (const addr of ["hello", "bc1qxyz", "0x52908400098527886E0F7030069857D2E4169EE7", "ztest1qqqqqqqq"]) {
    const v = validateTestnetAddress(addr);
    assert.equal(v.valid, false, addr);
    assert.match(v.reason ?? "", /unrecognized/i, addr);
  }
});
